### ISSUE TITLE
cert-manager: support overriding ACME HTTP-01 solver image ref

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/ansible-collection-containers#29]
## Context
The current cert-manager chart version is 1.7 and it doesn't have the ability to override ACME solver image ref.
This is requested from an air-gap customer.

## Solution
First, upgrade the chart version to 1.11> at least
https://github.com/cert-manager/cert-manager/commit/ea0bea9db054b73fca78e90dd815312a0b1c3593#diff-504397f76753139e76108f3e6a34f9f63788627dbf773b069f1c1c3ed347d811R195
Then, add one variable to set the image field.

**Comment by mpiscaer** [comment]
Should this issue not be in addressed in https://github.com/vexxhost/ansible-collection-kubernetes ?
